CC = gcc
CFLAGS = -c
OUTFLAGS = -o 

all: p1 p2 p3

p1:	p1.c
	$(CC) p1.c $(OUTFLAGS) prog1

runp1: 
	./prog1


p2:	p2.c
	$(CC) p2.c $(OUTFLAGS) prog2

runp2: 
	./prog2

p3:	p3.c
	$(CC) p3.c $(OUTFLAGS) prog3

runp2: 
	./prog3

p4:	p4.c
	$(CC) p4.c $(OUTFLAGS) prog4

runp2: 
	./prog4

clean:s
	rm *.o
	rm *.out
